name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up the environment
        run: |
          sudo ./.github/setup-ci.sh

      - name: Install the toolchain
        run: |
          # Install pre-compiled toolchain (for all distributions)
          xpm install @xpack-dev-tools/riscv-none-elf-gcc@14.2.0-3.1 --verbose --global

      - name: Set PATH
        run: |
          echo "$HOME/.local/xPacks/@xpack-dev-tools/riscv-none-elf-gcc/14.2.0-3.1/.content/bin" >> $GITHUB_PATH

      - name: Set RISCV_PREFIX
        run: |
          echo "RISCV_PREFIX=riscv-none-elf" >> $GITHUB_ENV

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Run the tests
        run: |
          make MODE=ci

      - name: Clean
        run: |
          make clean_all
